# Generated by Django 4.1 on 2022-08-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20220812_1926'),
        ('notification', '0003_alter_notification_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweetaction', to='tweets.tweet'),
        ),
    ]
