# Generated by Django 4.1 on 2022-08-30 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20220812_1926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_alter_notification_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='foruser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweetaction', to='tweets.tweet'),
        ),
    ]
